spring:
  config:
    import:
      - application-mysql.yml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate:
      sql: debug
      type: trace